### ISSUE TITLE
Implement LDAP authentication

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/plume_ynh#22]

**Comment by yalh76** [comment]
Not implemented for now : https://github.com/Plume-org/Plume/issues/312

**Comment by trinity-1686a** [comment]
It has now been implemented. The feature is not yet documented, but it will be shortly.

**Comment by yalh76** [comment]
so cool, I hope LDAP will be in next release ^^

**Comment by KitaitiMakoto** [comment]
Documentation about LDAP feature is here: https://docs.joinplu.me/environment/#ldap
