### ISSUE TITLE
Differences between install from web and from cli

### ISSUE THREAD

**Issue by Zykino** [YunoHost-Apps/plume_ynh#3]
I encountered different behavior when creating an instance from the admin web interface and from the cli.

1) On the web interface I can set a "Libellé pour plume" (the first option) but not in the cli.

2) The installation from the web interface fail immediately (but PACMAN continue to run endlessly). In the cli it's working after the fix on #1.
Log:
>2018-11-20 19:54:08,694: WARNING - unable to write 'random state'
>2018-11-20 19:54:08,696: WARNING - !!
>2018-11-20 19:54:08,697: WARNING -   's script has encountered an error. Its execution was cancelled.
>2018-11-20 19:54:08,697: WARNING - !!
>2018-11-20 19:54:08,698: WARNING - 

2) a. Shouldn't it be written "**Plume**'s script has encountered an error. Its execution was cancelled." (or installation, or, ...)
2) b. "unable to write 'random state'" may refer to something like https://stackoverflow.com/questions/94445/using-openssl-what-does-unable-to-write-random-state-mean. I searched for thoses files and removed them (one in "/usr/share/yunohost/yunohost-config/ssl/.rnd" and one in "/root/.rnd") but the bug is still here.

**Comment by anmol26s** [comment]
1. This is by core in the Yunohost. On Command line it don't show the label option. You can request that feature by opening an issue. But as most of the time more advance users or app testers use it for debugging form cmd it was never thought of. 
2. I should fix this, its a bug if app fails without installing rust.
2 a. I did not get your point here. The app don't say failing message after fail?
3 b. This is actually related to the app? I don't think so. You should write on forum.yunohost.org as other people can also have there thoughts on this.

**Comment by Zykino** [comment]
1) I didn't know, will see with them
2) a. It look like the first word from the middle line of the log is missing. Is it a Yunohost bug or a did a variable wasn't setted?
2) b. I thought it was the reason of the error (my quick search from the first line of the log).

**Comment by anmol26s** [comment]
2 a. Yes there should be app name. I don't know why there is not app name in logs. This actually is not related to the app but maybe particular to your system or some bug in yunohost. Check if other apps gives the same error.
3. b Have you solve the error? This is again not related to the app.

**Comment by anmol26s** [comment]
Hopefully 2 should be fixed now. If the error is still there please reopen or comment.
Other error not look related, but if you find it related please reopen it.
