### ISSUE TITLE
/notifications internal server error (after deleting a blog and an article)

### ISSUE THREAD

**Issue by deckname** [YunoHost-Apps/plume_ynh#58]
I have two accounts. On one account I posted an article in a blog, then deleted the blog and article and made a new blog and article. Before /notifications worked on this account, now it doesn't, when I click the bell it doesn't load and when I go to the URL directly as well. It gives a 500 internal server error. 

On a different account I can still view the /notifications url and receive notifications. 

Plume 0.4.0-alpha-4
- **Operating system:** Debian 9
- **Web Browser:** Firefox and Chromium

**Comment by yalh76** [comment]
Hi, 

have you check at the upstream app repository ?

**Comment by deckname** [comment]
> Hi,
> 
> have you check at the upstream app repository ?

no probably not because I don't know what you mean by that.

**Comment by yalh76** [comment]
well yunohost only package apps made by others. We don't develop them.

**Comment by deckname** [comment]
Yes I made a bug report with the plume project as well. 
Thanks!
