### ISSUE TITLE
Instance name cannot contain "-" during installation

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/plume_ynh#69]
### Describe the bug

I attempted to install Plume and entered "Kuba Orlik - blog" for the instance name.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.1.7.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.6.0~ynh1

### Steps to reproduce

Try to install Plume from webadmin panel and enter a name that contains ` - ` in the Instance Name field. An error pops up.

### Expected behavior

The app installs

### Logs

https://paste.yunohost.org/raw/evocudewaw

**Comment by yalh76** [comment]
weel, it's more because there are space in your instance name.... That's the issue, I will do a PR to let have spaces in instance name if possible

**Comment by kuba-orlik** [comment]
Surprisingly, spaces were ok. But not dashes surrounded by spaces
