### ISSUE TITLE
v0.7.0 is out!

### ISSUE THREAD

**Issue by KitaitiMakoto** [YunoHost-Apps/plume_ynh#76]
Hi,

We, Plume maintainers, released the new version of Plume: v0.7.0!
https://fediverse.blog/~/PlumeDev/Plume%200.7.0%20is%20out!

Can you release the YunoHost version?

**Comment by KitaitiMakoto** [comment]
Also v0.7.1 was released: https://fediverse.blog/~/PlumeDev/Plume%200.7.1%20is%20out

**Comment by yalh76** [comment]
upgraded !!

**Comment by KitaitiMakoto** [comment]
Great, thanks!
